
kv_namespaces = [{ binding = "kv4email", id = "xxxxxxxxxx" }]
routes = [ { pattern = "chiase.sale", custom_domain = true }]
website_name = "Your Website Name"
email_domain = '["chiase.sale"]'
contact_email = "contact@chiase.sale"
abuse_email = "abuse@chiase.sale"
custom_email_domain = '["ct.chiase.sale"]'
